 --ALTER TABLE perfis ADD COLUMN ativo BOOLEAN;

 -- ALTER TABLE cursos ADD COLUMN ativo BOOLEAN;

 -- ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN;

 -- ALTER TABLE topicos ADD COLUMN ativo BOOLEAN; */